# Generated by Django 5.0.1 on 2024-01-31 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('entry', models.TextField()),
                ('stress_level', models.PositiveBigIntegerField(default=0)),
                ('current_emotion', models.CharField(choices=[('Normal', 'normal'), ('Tired', 'tired'), ('Angry', 'angry'), ('Sad', 'sad')], max_length=250)),
                ('whats_stressing_you', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
