# Generated by Django 5.0.1 on 2024-02-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='user',
            new_name='journal_user',
        ),
    ]
