# Generated by Django 5.0.1 on 2024-02-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_journal_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='title',
            new_name='feeling',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='entry',
            new_name='journal_text',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='whats_stressing_you',
            new_name='mood',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='current_emotion',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_rating',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='stress_level',
        ),
    ]
