# Generated by Django 5.0.1 on 2024-02-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_rename_title_journal_feeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='rating',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
