# Generated by Django 5.0.1 on 2024-02-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_journal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='rating',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
