# Generated by Django 5.0.1 on 2024-01-27 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_goal', models.CharField(choices=[('I wanna reduce stress', 'I wanna reduce stress'), ('I wanna try AI Therapy', 'I wanna try AI Therapy'), ('I want to cope with trauma', 'I want to cope with trauma'), ('I want to be a better person', 'I want to be a better person'), ('Just trying out the website', 'Just trying out the website')], max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'other')], max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral')], max_length=100)),
                ('is_professional_help', models.BooleanField()),
                ('is_physical_distress', models.BooleanField()),
                ('sleep_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('poor', 'Poor'), ('fair', 'Fair'), ('worse', 'Worse')], max_length=100)),
                ('medications', models.CharField(choices=[('prescribed medication', 'Prescribed Medication'), ('pharmacist', 'Pharmacist'), ("i'm not taking any", "I'm not taking any"), ('prefer not to say', 'Prefer not to say')], max_length=100)),
                ('other_mental_symptom', models.TextField()),
                ('stress_level', models.PositiveIntegerField()),
                ('expression_analysis', models.TextField()),
                ('health_goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.healthgoal')),
            ],
        ),
    ]
