# Generated by Django 5.0.1 on 2024-02-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_assessment_expression_analysis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthgoal',
            old_name='health_goal',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='health_goal',
            field=models.CharField(choices=[('I wanna reduce stress', 'I wanna reduce stress'), ('I wanna try AI Therapy', 'I wanna try AI Therapy'), ('I want to cope with trauma', 'I want to cope with trauma'), ('I want to be a better person', 'I want to be a better person'), ('Just trying out the website', 'Just trying out the website')], max_length=250),
        ),
    ]
