# Generated by Django 5.0.1 on 2024-02-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthgoal',
            name='name',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='is_physical_distress',
            field=models.IntegerField(choices=[(2, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='is_professional_help',
            field=models.IntegerField(choices=[(2, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='medications',
            field=models.IntegerField(choices=[(4, 'Prescribed Medication'), (3, 'Pharmacist'), (2, "I'm not taking any"), (1, 'Prefer not to say')]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mood',
            field=models.IntegerField(choices=[(5, 'Over Joyed'), (4, 'Happy'), (3, 'Neutral'), (2, 'Sad'), (1, 'Depressed')]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sleep_quality',
            field=models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Poor'), (2, 'Fair'), (1, 'Worse')]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='stress_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
