# Generated by Django 5.0.1 on 2024-02-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_remove_healthgoal_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthGoal',
        ),
    ]
