# Generated by Django 5.0.1 on 2024-10-22 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_delete_healthgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssessmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_goal', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('mood', models.IntegerField()),
                ('is_professional_help', models.IntegerField()),
                ('is_physical_distress', models.IntegerField()),
                ('sleep_quality', models.IntegerField()),
                ('medications', models.IntegerField()),
                ('other_mental_symptom', models.TextField()),
                ('stress_level', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
    ]
